### ISSUE TITLE
Training Detail

### ISSUE THREAD

**Issue by SmallYour** [YuanEZhou/Grounded-Image-Captioning#5]
Hi, I am trying to reproduce the baseline(Topdown in Flickr 30k, with CIDEr optimization in RL phase) in your paper, and I used different kinds of code including yours, but I failed, The result of CIDEr score is around 60, can not reach the similar result in your paper (over 67), can you share the detailed training setting? 

Thanks!

**Comment by YuanEZhou** [comment]
Strange! I will check the training setting later and give you feedback within this week.

**Comment by YuanEZhou** [comment]
Sorry for the later reply.  I am running the code and the CIDEr score is around 64 after 60 epochs and I think it will reach 67 after 110 epochs. 
![捕获](https://user-images.githubusercontent.com/17077323/119285204-20f3aa00-bc74-11eb-9f74-cf1bbe5792af.PNG)

To  reproduce the baseline (Topdown in Flickr 30k, with CIDEr optimization in RL phase), please try:
`python train.py --id CE --caption_model topdown --input_json data/flickrtalk.json --input_fc_dir data/flickrbu/flickrbu_fc --input_att_dir data/flickrbu/flickrbu_att  --input_box_dir data/flickrbu/flickrbu_box  --input_label_h5 data/flickrtalk_label.h5 --batch_size 29 --learning_rate 5e-4 --learning_rate_decay_start 0 --scheduled_sampling_start 0 --checkpoint_path log/CE --save_checkpoint_every 1000 --val_images_use -1 --max_epochs 30`
and then
`python train.py --id sc-cider-CE --caption_model topdown --input_json data/flickrtalk.json --input_fc_dir data/flickrbu/flickrbu_fc --input_att_dir data/flickrbu/flickrbu_att  --input_box_dir data/flickrbu/flickrbu_box  --input_label_h5 data/flickrtalk_label.h5 --batch_size 29 --learning_rate 5e-5 --start_from log/CE   --checkpoint_path log/sc-cider-CE  --save_checkpoint_every 1000 --language_eval 1 --val_images_use -1 --self_critical_after 30  --max_epochs  110      --cider_reward_weight  1
--ground_reward_weight   -1 
`

**Comment by SmallYour** [comment]
According to your code, we successfully reproduce the performance in your paper. Thanks for replying.
