### ISSUE TITLE
Can you release how to train the pos-scan model?

### ISSUE THREAD

**Issue by liujiaheng** [YuanEZhou/Grounded-Image-Captioning#8]
Great work. Looking forward to your reply.

**Comment by YuanEZhou** [comment]
Hi @liujiaheng, the code of modified SCAN model(pos-scan) is under Grounded-Image-Captioning/misc/SCAN/ dir and I followed the training script of [SCAN](https://github.com/kuanghuei/SCAN) repository.

**Comment by liujiaheng** [comment]
OK, thanks.
